# NumPy 
#### Libaray for numerical python computation
Fundamental package for array computing in Python

In [1]:
Marks = [10,20,20]

In [2]:
Marks*2

[10, 20, 20, 10, 20, 20]

In [4]:
Marks + [2]

[10, 20, 20, 2]

In [7]:
type(Marks)

list

In [9]:
import numpy as np

In [10]:
arr = np.array(Marks)

In [11]:
arr*2

array([20, 40, 40])

In [12]:
arr+2

array([12, 22, 22])

In [20]:
#n dimensional array
type(arr)

numpy.ndarray

In [13]:
##Array are always made up of homogenous data type

In [14]:
np.arange(10,16,1)

array([10, 11, 12, 13, 14, 15])

In [16]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [17]:
np.arange(10,12,0.6)

array([10. , 10.6, 11.2, 11.8])

In [19]:
#num to generated between a range
np.linspace(1,11,6)

array([ 1.,  3.,  5.,  7.,  9., 11.])

In [21]:
###****array - mean list of elements of similar data type*****

In [23]:
lst = list(range(1,11,2))
lst

[1, 3, 5, 7, 9]

In [63]:
a=[]
for ele in lst:
    b=ele**2
    a.append(b)
    i+=1
print(a)    

[1, 9, 25, 49, 81]


In [75]:
%timeit [ele**2 for ele in lst]

182 ns ± 0.26 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [147]:
[ele**2 for ele in lst]

[1, 9, 25, 49, 81]

In [69]:
sq = np.array(lst)

In [74]:
%timeit sq**2

195 ns ± 1.85 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [82]:
##Access element of array
arr= np.arange(10,25,2)
print(arr)
print(arr[0])
print(arr[-1])
print(arr[3:4])
print(arr[:4])
print(arr[5:])
##[ -- included ) excluded

[10 12 14 16 18 20 22 24]
10
24
[16]
[10 12 14 16]
[20 22 24]


In [83]:
np.array([10,21.1])

array([10. , 21.1])

In [85]:
np.array(['he',21.1])

array(['he', '21.1'], dtype='<U32')

In [86]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24])

In [89]:
arr[2]=100
arr

array([ 10,  12, 100,  16,  18,  20,  22,  24])

In [90]:
print(arr)

[ 10  12 100  16  18  20  22  24]


# 1d array = 1 row (1*n) = Vector
# 2d array = 2 rows (2*n) = matrix
# 3d..4d..5d....= m rows>2 = (m rows*n columns) = tensors

In [101]:
nLst = [[1,2,3],[4,5,6]]

In [102]:
len(nLst)

2

In [94]:
arr2d = np.array(nLst)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
print(arr2d) ##matrix

[[1 2 3]
 [4 5 6]]


In [99]:
arr2d*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [100]:
arr2d+2

array([[3, 4, 5],
       [6, 7, 8]])

In [103]:
arr2d.size

6

In [96]:
dLst = [[1,2,3],[4,5,6],[7,8,9]]

In [112]:
arrd = np.array(dLst) ## Tensor
print(arrd)
arrd

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
arrd.size

9

In [114]:
arr2d.shape

(2, 3)

In [115]:
type(arr2d.shape)

tuple

In [116]:
arr2d.ndim

2

In [117]:
arrd.ndim

2

In [118]:
arrd[2][2]

9

In [119]:
arrd[0,0]

1

In [ ]:
# arrd[1,1]

In [121]:
arr

array([ 10,  12, 100,  16,  18,  20,  22,  24])

In [122]:
arr.ndim

1

In [123]:
arr.shape

(8,)

In [127]:
np.array([1,2])
np.array([[1,2]]).shape
np.array([[[1,2]]]).shape

(1, 1, 2)

In [130]:
a= np.array([1,2,3,4,5], ndmin=2)
a

array([[1, 2, 3, 4, 5]])

# reshape


In [132]:
m1=np.arange(10,30,1)
m1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [133]:
m1.shape

(20,)

In [136]:
m1.ndim


1

In [137]:
m1.reshape((4,5))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [138]:
m1.reshape((5,4))

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [139]:
m1.reshape((2,10))

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [140]:
m1.reshape((4,4))

ValueError: cannot reshape array of size 20 into shape (4,4)

In [141]:
np.arange(16).reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [143]:
np.arange(16).reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [144]:
np.arange(16).reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])